version: 2

sources:
  - name: raw_data
    schema: raw_data
    tables:
      - name: groups
        columns:
          - name: "group_id"

      - name: users
        columns:
          - name: "user_id"

      - name: events
        columns:
          - name: "event_id"
          - name: "event_start_at"

      - name: venues
        columns:
          - name: "venue_id"