meetup_dbt_project:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: MEETUP_ANALYTICS
      threads: 1
      warehouse: COMPUTE_WH
      database: MEETUP_DB
  target: dev
